### ISSUE TITLE
aw-server-rust does not accept `--testing` flag

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/aw-server-rust#102]
Tried running aw-server-rust in v0.9.2 with `--testing` but it didn't use the testing port.

**Comment by xylix** [comment]
Yeah currently you need to run it with `cargo run aw-server` from the aw-server-rust project root to run with testing params. This would be useful to support though.

**Comment by ErikBjare** [comment]
You should get the same result by setting `ROCKET_ENV=development`, but setting it with a flag is what we do in aw-qt so it kinda needs to be supported.

I tried looking at `config.rs` but it looks like we currently use Rocket `Environment` to detect testing/non-testing mode everywhere which makes it messy to change. Might be easy for @johan-bjareholt though who knows the code.

**Comment by johan-bjareholt** [comment]
@ErikBjare The reason why the change would require quite a bit of rework of the code is because rocket Environment is stateless while if we want to provide an option into this code we would have to provide a state (if --testing is set or not) when creating an AwConfig.

I guess it was just a matter of time before we would have to do something like this though, will probably be needed for more CLI options and such in the future as well.

**Comment by johan-bjareholt** [comment]
Solved in #107
