### ISSUE TITLE
Error: No db found in sync folder

### ISSUE THREAD

**Issue by shubham-iapp** [ActivityWatch/aw-server-rust#466]
When i run `./aw-sync`

I get the error : 

> Error: "No db found in sync folder \"/home/iapp/ActivityWatchSync/php-iapp-pc-1\""

Here is the screenshot for the same:
![2024-02-08_17-26](https://github.com/ActivityWatch/aw-server-rust/assets/149566132/1f5b2063-0851-4ebf-a2a0-42efb8b1643f)

PS: I am using the latest pre release version `v0.12.3b16`

**Comment by egstatsml** [comment]
same question here with `aw-server-rust v.0.13.1` and `aw-sync v0.1`

**Comment by egstatsml** [comment]
scratch that, I was using the AUR repo for activity watch. Just rebuilt manually and is working for me on commit `82345cfc5371c673a9bc2b5284530ae8c180153d`

**Comment by krzysid** [comment]
I think the issue is in `aw-sync/src/sync.wrapper.rs` lines 44-49:
```
// filter out dbs that are smaller than 50kB (workaround for trying to sync empty database
// files that are spuriously created somewhere)
let dbs = dbs
    .into_iter()
    .filter(|entry| entry.metadata().map(|m| m.len() > 50_000).unwrap_or(false))
    .collect::<Vec<_>>();
```
Default, empty database is only ~44kB in size. This is not a problem during the first launch, as aw-sync doesn't check for the file size when there is no synced database available, it just copies the small database without issues. However, if aw-sync is closed before it can synchronize a larger database (52kB, as SQLite DBs seems to grow in 8kB steps), it will then first check for synced databases that have data - which it can't find, thus it crashes.
I'm not sure why the check is even in-place, if aw-sync already picks the largest available database, so empty databases should be no problem.
A workaround for now would be probably to not run aw-sync until the database is larger than 50kB (5-10 minutes of usage time), or remove the database file from sync directory after quitting if it's smaller than 44kB. a `--skip-db-size-check` parameter could be useful also.

**Comment by ErikBjare** [comment]
@krzysid Thanks for pointing this out, you're probably right that the check can be removed. I will do so immediately.
